// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAX8lc0hifwFQQJVqAjQ6DOu5tUO4Bcrh4',
    appId: '1:804365493941:web:ce9fffa316ae8d390340fc',
    messagingSenderId: '804365493941',
    projectId: 'project-6346778542392807865',
    authDomain: 'project-6346778542392807865.firebaseapp.com',
    databaseURL: 'https://project-6346778542392807865-default-rtdb.firebaseio.com',
    storageBucket: 'project-6346778542392807865.appspot.com',
    measurementId: 'G-GEQRG5QY8P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0UIvMFppLsBIXYMDiu1g0ltyJUHqUnr8',
    appId: '1:804365493941:android:6490ab3c48818af20340fc',
    messagingSenderId: '804365493941',
    projectId: 'project-6346778542392807865',
    databaseURL: 'https://project-6346778542392807865-default-rtdb.firebaseio.com',
    storageBucket: 'project-6346778542392807865.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALu-cuLyDRqCzV2hYjXTLGGRthesw6V_U',
    appId: '1:804365493941:ios:76a7a9def7173de90340fc',
    messagingSenderId: '804365493941',
    projectId: 'project-6346778542392807865',
    databaseURL: 'https://project-6346778542392807865-default-rtdb.firebaseio.com',
    storageBucket: 'project-6346778542392807865.appspot.com',
    iosBundleId: 'com.example.game2048',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyALu-cuLyDRqCzV2hYjXTLGGRthesw6V_U',
    appId: '1:804365493941:ios:d1af3c0e4ef16ed20340fc',
    messagingSenderId: '804365493941',
    projectId: 'project-6346778542392807865',
    databaseURL: 'https://project-6346778542392807865-default-rtdb.firebaseio.com',
    storageBucket: 'project-6346778542392807865.appspot.com',
    iosBundleId: 'com.example.game2048.RunnerTests',
  );
}
